/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tTube;

/**
 *
 * @author 1class-040
 */
public class tTubeGetMsg extends javax.swing.JFrame {

	public tTubeGetMsg() {
        initComponents("익명의 누군가","안녕");
    }
	
    public tTubeGetMsg(String Nickname, String msg) {
        initComponents(Nickname, msg);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(String Nickname, String msg) {
    	
    	setResizable(false);

        jPanel1 = new javax.swing.JPanel();
        lbGetNickname = new javax.swing.JLabel();
        lbGetTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taGetMsg = new javax.swing.JTextArea();
        imgBg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(360, 420));

        jPanel1.setLayout(null);

        lbGetNickname.setFont(new java.awt.Font("나눔바른고딕", 0, 14)); // NOI18N
        lbGetNickname.setForeground(new java.awt.Color(0, 51, 124));
        lbGetNickname.setText("BJ라이브7");
        jPanel1.add(lbGetNickname);
        lbGetNickname.setBounds(150, 50, 80, 40);
        lbGetNickname.setText(Nickname);

        lbGetTitle.setFont(new java.awt.Font("나눔바른고딕", 1, 14)); // NOI18N
        lbGetTitle.setForeground(new java.awt.Color(0, 51, 124));
        lbGetTitle.setText("보낸 사람 :");
        jPanel1.add(lbGetTitle);
        lbGetTitle.setBounds(80, 50, 70, 40);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        taGetMsg.setColumns(20);
        taGetMsg.setFont(new java.awt.Font("나눔바른고딕", 0, 13)); // NOI18N
        taGetMsg.setLineWrap(true);
        taGetMsg.setRows(5);
        taGetMsg.setWrapStyleWord(true);
        taGetMsg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        taGetMsg.setText(msg);
        taGetMsg.setEditable(false);
        
        jScrollPane1.setViewportView(taGetMsg);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(80, 110, 200, 160);

        imgBg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tTube/images/imgMsgBg.png"))); // NOI18N
        imgBg.setText("jLabel1");
        jPanel1.add(imgBg);
        imgBg.setBounds(0, -20, 360, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tTubeGetMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tTubeGetMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tTubeGetMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tTubeGetMsg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tTubeGetMsg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel imgBg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbGetNickname;
    private javax.swing.JLabel lbGetTitle;
    private javax.swing.JTextArea taGetMsg;
    // End of variables declaration                   
}

